### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by chennylmf** [Z4nzu/hackingtool#1]
Hi, this is really an amazing tool with so many functions integrated
I came across this error after successful installation 

root@kali:~/hackingtool# hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 1681, in <module>
    os.chdir("/home/{0}/Desktop/".format(uname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/None/Desktop/'

**Comment by Z4nzu** [comment]
Thank you for downloading and installing this tool....please try to run as a root 

```
root@kali:~ sudo hackingtool
```
After that is it not working than I'll fix some errors

**Comment by chennylmf** [comment]
thanks for your reply. yea, i have run it as root but still having the same issue

**Comment by Z4nzu** [comment]
I have fixed error please remove old download files and install new git file.after that if you have an error than message me on twitter...Thank you 😊

**Comment by amerbashar** [comment]
thank you for an amazing tool
I came across this error after successful installation

Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>
    os.mkdir(archive)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by mrmacin** [comment]
hey i am also getting the same problem

**Comment by lord-zeus** [comment]
@amerbashar having same issue here any way around it ?

**Comment by lord-zeus** [comment]
hey @amerbashar & @mrmacin 
check his solution 
https://github.com/Z4nzu/hackingtool/issues/129#issuecomment-802379053
worked for me

**Comment by H8C0R3** [comment]
i have the same problem
