### ISSUE TITLE
it doesnt work 

### ISSUE THREAD

**Issue by hoiboiasdjflk** [Z4nzu/hackingtool#102]
line 97
    print(f"Your Default Path Is:- {autopath}")
                                             ^
SyntaxError: invalid syntax

**Comment by Z4nzu** [comment]
>  line 97
>     print(f"Your Default Path Is:- {autopath}")
>                                              ^
> SyntaxError: invalid syntax
> 

Try to reinstall or update tool. I think you tried to changes in tool script and this error come..!!
