### ISSUE TITLE
How do we use it?

### ISSUE THREAD

**Issue by XenonPoison** [Z4nzu/hackingtool#103]

**Comment by Z4nzu** [comment]
Please follow all the steps followed by Readme.md and for specific tool there is a link for each tool you can refer that also 😊

**Comment by RetickYadav** [comment]
Ok bro

Sent from Yahoo Mail on Android 
 
  On Thu, 5 Nov 2020 at 2:46 pm, Mr.Z4nzu<notifications@github.com> wrote:   


Closed #103.
