### ISSUE TITLE
ummm how do i fix this

### ISSUE THREAD

**Issue by HHsenpai-spec** [Z4nzu/hackingtool#106]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/73730929/98630040-326b0980-2355-11eb-9788-5a34531683f1.png)

**Comment by Z4nzu** [comment]
Please update tool and try ..!! 😊
