### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by xKoolaidman97x** [Z4nzu/hackingtool#125]
**Describe the bug**
Tried to run after installation, and was met with this error:

root@MobileKillerPC:/home/leo/Documents/Hacking/hackingtool# hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>
    os.mkdir(archive)
FileNotFoundError: [Errno 2] No such file or directory: "'/home/leo/Documents/Hacking/hackingtool'\n"

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.10

**Comment by Z4nzu** [comment]
Please refer #108 closed issue. Hope It'll solve your problems 🙂

**Comment by aramsoft89** [comment]
python2 hackingtool.py         
  File "hackingtool.py", line 92
    print(f"Successfully Set Path to: {inpath}")
                                              ^
SyntaxError: invalid syntax


system :- kali linux

**Comment by aramsoft89** [comment]
python3 hackingtool.py                                                                                                                                         1 ⨯
Traceback (most recent call last):
  File "/home/kali1/Desktop/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/home/kali1/Desktop/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax



system :- kali linux

**Comment by aramsoft89** [comment]
Thanks for helpe me

**Comment by botRobot8159** [comment]
I need a Fortnite account for a ps4
