### ISSUE TITLE
FileNotFoundError 

### ISSUE THREAD

**Issue by lord-zeus** [Z4nzu/hackingtool#129]
Traceback (most recent call last):
File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in 
os.mkdir(archive)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by CsweetREI** [comment]
Locate hackingtoolpath.txt
rm hackingtoolpath.txt
That should fix it.
Then when you run hackingtool choose 2

**Comment by lord-zeus** [comment]
thanks @CsweetREI

**Comment by kibefirst** [comment]
> Locate hackingtoolpath.txt rm hackingtoolpath.txt That should fix it. Then when you run hackingtool choose 2

Thanks bro

**Comment by taiyebnirjhar** [comment]
unabled to find any file named hackingtoolpath.txt

**Comment by simsimman** [comment]
> unabled to find any file named hackingtoolpath.txt
same with me. I think the file can be generated only after you run the code and we need to run it without that error...I fixed it by moving the original hackingtool folder to that path (/usr/share/doc)
