### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AlbBoy** [Z4nzu/hackingtool#13]
boxes not found
after presing 1 for install it goes back as if I pressed 99 not 1

**Comment by Z4nzu** [comment]
Please install requirements using 
```
Pip3 install -r requirements.txt
```

**Comment by AlbBoy** [comment]
already done 
    On Wednesday, July 8, 2020, 12:14:33 PM GMT+2, Mr.Z4nzu <notifications@github.com> wrote:  
 
 


Please install requirements using
Pip3 install -r requirements.txt

**Comment by kiikoh** [comment]
Having same issue, clean install of kali from windows store. I ran all commands in readme

**Comment by surjeetsujal0010** [comment]
Hello......

**Comment by surjeetsujal0010** [comment]
I want to contact you please tell how may i can contact you...

**Comment by aakashbillyass** [comment]
What?

**Comment by Z4nzu** [comment]
Through Twitter please contact me there you can message me there
I'd @_Zinzu07

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by awanishtiwari97** [comment]
call me or  whatsapp me at 9792060080

**Comment by surjeetsujal0010** [comment]
Sir i want to contact you how may i can contact you.

Please tell

**Comment by aakashbillyass** [comment]
What about instagram

**Comment by surjeetsujal0010** [comment]
Please pick up the call sir

**Comment by Z4nzu** [comment]
I'm not using instagram please message me on twitter I have enable message on twitter..

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by surjeetsujal0010** [comment]
Sir please reply on whatsapp

**Comment by surjeetsujal0010** [comment]
Hello.....

**Comment by surjeetsujal0010** [comment]
Helllo....

**Comment by Z4nzu** [comment]
Hie please tell me what ??

**Comment by surjeetsujal0010** [comment]
Please reply....sir.
I want to ask some important puestion

**Comment by Z4nzu** [comment]
> Please reply....sir.
> I want to ask some important puestion

I have reply you please ask ..

**Comment by surjeetsujal0010** [comment]
Give me your no please sir.....

**Comment by aakashbillyass** [comment]
What is your Twitter name

**Comment by surjeetsujal0010** [comment]
Or i can contact you on instagram.

**Comment by aakashbillyass** [comment]
Hello

**Comment by surjeetsujal0010** [comment]
I am not twitter...

**Comment by surjeetsujal0010** [comment]
Only whatsapp

**Comment by surjeetsujal0010** [comment]
Or please tell me the instagram

bruteforce termux code.

**Comment by surjeetsujal0010** [comment]
Hello........

**Comment by Z4nzu** [comment]
@_Zinzu07
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by aakashbillyass** [comment]
I'm in twitter

**Comment by aakashbillyass** [comment]
Imcupcakegamer is my username

**Comment by surjeetsujal0010** [comment]
Can you can provide me the bruteforce code of instagram.

**Comment by surjeetsujal0010** [comment]
Please provide me the code of instagram bruteforce code

**Comment by Z4nzu** [comment]
![Screenshot_2020-07-11-20-25-48-650_com.twitter.android.lite.jpg](https://user-images.githubusercontent.com/25708027/87226930-caabae80-c3b4-11ea-85e7-9cb79d631197.jpg)
Please You send me message because you have not enable message features...
My Twitter I'd @_Zinzu07

**Comment by surjeetsujal0010** [comment]
Do you have the code or not.

**Comment by surjeetsujal0010** [comment]
You have the code or not.

**Comment by Z4nzu** [comment]
I don't have an personal code but I have mentioned tools in socialmedia attack that can be helpful to you for hacking instagram..

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by kiikoh** [comment]
Don't know what's going on up there... but I'm having this issue with a fresh install of Kali Linux on WSL2. Getting boxes not found for nearly every script I try to run, i've installed it using pip3 so dont know what the problem is

**Comment by Z4nzu** [comment]
> boxes not found
> after presing 1 for install it goes back as if I pressed 99 not 1

 ```
sudo pip3 install boxes
```

**Comment by Z4nzu** [comment]
> Don't know what's going on up there... but I'm having this issue with a fresh install of Kali Linux on WSL2. Getting boxes not found for nearly every script I try to run, i've installed it using pip3 so dont know what the problem is

```
sudo pip3 install boxes
```

**Comment by kiikoh** [comment]
![Pic](https://i.imgur.com/95obKTT.png)

**Comment by kiikoh** [comment]
![](https://i.imgur.com/EQuGwZC.png)
