### ISSUE TITLE
How to completely remove and re-install like fresh 

### ISSUE THREAD

**Issue by FrankensteinEvil0069** [Z4nzu/hackingtool#131]
Hey, devloper of this tool 
This tool is amazing but I have to reinstall it again like  fresh because my friend messed the whole file of this tool and i cant figure out where to restore. I just need to know how to completely remove and re-install like fresh because when i delete the directory and   extract the tool again in the terminal then also some files remain installed somewhere on my laptop and break the installation 

PLEASE HELP !!!!!!!

**Comment by Riz0300** [comment]
Instal

**Comment by shane89420** [comment]
Your tool works but when I try installing fatrat it always fails to
actually install the dependency
