### ISSUE TITLE
Won't let me run shell says permission denied


### ISSUE THREAD

**Issue by shane89420** [Z4nzu/hackingtool#135]
I'm logged into kali as root yet this still refuses to let me run the setup.anyone have ideas

**Comment by Greatest125** [comment]
Can you please provide more detail and context? What is the terminal output when you try to run the setup? Maybe provide some screenshots? Is this a clean install? What machine are you on?

**Comment by shane89420** [comment]
Its all good brother I got it to run but fatrat still won't install... doesn't load dependency and when I ran the script it still won't work...ideas I'm running Kali clean fresh build
