### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hueychen27** [Z4nzu/hackingtool#136]
Error

1. Type in '`bash install.sh`'
2. Type in '`1`'
3. Wait

`
   ▄█    █▄       ▄████████  ▄████████    ▄█   ▄█▄  ▄█  ███▄▄▄▄      ▄██████▄           ███      ▄██████▄   ▄██████▄   ▄█       
  ███    ███     ███    ███ ███    ███   ███ ▄███▀ ███  ███▀▀▀██   ███    ███      ▀█████████▄ ███    ███ ███    ███ ███       
  ███    ███     ███    ███ ███    █▀    ███▐██▀   ███▌ ███   ███       █▀          ▀███▀▀██ ███    ███ ███    ███ ███       
 ▄███▄▄▄▄███▄▄   ███    ███ ███         ▄█████▀    ███▌ ███   ███  ▄███                 ███   ▀ ███    ███ ███    ███ ███       
▀▀███▀▀▀▀███▀  ▀███████████ ███        ▀▀█████▄    ███▌ ███   ███ ▀▀███ ████▄           ███     ███    ███ ███    ███ ███       
  ███    ███     ███    ███ ███    █▄    ███▐██▄   ███  ███   ███   ███    ███          ███     ███    ███ ███    ███ ███       
  ███    ███     ███    ███ ███    ███   ███ ▀███▄ ███  ███   ███   ███    ███          ███     ███    ███ ███    ███ ███▌    ▄ 
  ███    █▀      ███    █▀  ████████▀    ███   ▀█▀ █▀    ▀█   █▀    █          ▄████▀    ▀██████▀   ▀██████▀  █████▄▄██ 
                                         ▀                                                                            ▀         
                                    https://github.com/Z4nzu/hackingtool 
                                   [!] This Tool Must Run As ROOT [!]

 Select Best Option : 

              [1] Kali Linux / Parrot-Os 
              [0] Exit 
Z4nzu >> 1
[*] Checking Internet Connection ..
[✔] Loading ... 
Hit:1 http://dl.google.com/linux/webdesigner/deb stable InRelease
Ign:2 https://storage.googleapis.com/cros-packages/89 buster InRelease                               
Hit:3 https://deb.debian.org/debian buster InRelease                                                 
Hit:4 https://storage.googleapis.com/cros-packages/89 buster Release                                 
Hit:5 https://deb.debian.org/debian-security buster/updates InRelease                                
Hit:6 https://repo.steampowered.com/steam stable InRelease                                           
Hit:7 https://dl.winehq.org/wine-builds/debian buster InRelease                                      
Hit:8 https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./ InRelease      
Reading package lists... Done
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (18.1-5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[✔] Checking directories...
[✔] Installing ...

fatal: could not create work tree dir '/usr/share/doc/hackingtool': Permission denied
install.sh: line 61: hackingtool: Is a directory
cp: -r not specified; omitting directory 'hackingtool'
rm: cannot remove 'hackingtool': Is a directory

[✔] Trying to installing Requirements ...
Requirement already satisfied: lolcat in /usr/local/lib/python3.7/dist-packages (1.4)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
figlet is already the newest version (2.2.5-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: boxes in /usr/local/lib/python3.7/dist-packages (0.0.0)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
boxes is already the newest version (1.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: flask in /usr/local/lib/python3.7/dist-packages (2.0.0)
Requirement already satisfied: Werkzeug>=2.0 in /usr/local/lib/python3.7/dist-packages (from flask) (2.0.0)
Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.7/dist-packages (from flask) (8.0.0)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.7/dist-packages (from flask) (3.0.0)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.7/dist-packages (from flask) (2.0.0)
Requirement already satisfied: MarkupSafe>=2.0.0rc2 in /usr/local/lib/python3.7/dist-packages (from Jinja2>=3.0->flask) (2.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.26.4)
[✘] Installation Failed !!! [✘]`

 - OS: Chrome Os
 - Browser Chrome

Help me fix issue.

**Comment by Z4nzu** [comment]
Try with root user it'll not give error and try to find solution in closed issue

**Comment by hueychen27** [comment]
Thanks. All I had to do was run `sh` and type my password to become root.
