### ISSUE TITLE
python3: can't open file '/usr/share/doc/hackingtool/hackingtool.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by amzarsyaf2002** [Z4nzu/hackingtool#137]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Greatest125** [comment]
See this: https://github.com/Z4nzu/hackingtool/issues/108

In the future, please search prior issues before creating one yourself to cut down on duplicates.
