### ISSUE TITLE
Hackingtool

### ISSUE THREAD

**Issue by MarrMu-KoHTeT** [Z4nzu/hackingtool#140]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Love you all buddy

**Describe alternatives you've considered**

**Additional context**

**Comment by AKIMITSU1** [comment]
Help please
[*] Checking Internet Connection ..
[✔] Loading ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[✔] Checking directories...
[✔] Installing ...

fatal: could not create leading directories of '/usr/share/doc/hackingtool': Read-only file system

[✔] Trying to installing Requirements ...
[✘] Installation Failed !!! [✘]
$

**Comment by shane89420** [comment]
Copy the script from GitHub it should work fine

**Comment by AKIMITSU1** [comment]
What script
Bte yes im akimitsu1

**Comment by shane89420** [comment]
Go to GitHub and there will be installation instructions..copy and paste bro
