### ISSUE TITLE
hackingtool problem

### ISSUE THREAD

**Issue by cnkhka96** [Z4nzu/hackingtool#143]
Hi team,
i have this problem when a run hackingtool cmd in my kali linux after the installation steps: 
hackingtool                                                                     
Traceback (most recent call last):                                                                                             
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>                                                      
    os.mkdir(archive)                                                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/root/pentest/Bureau/Hacking tools'                                   
root@pentest:/home/pentest/Bureau/hackingtool#                                                                                 
 please, can someone help?
thanks.

**Comment by W1LDN16H7** [comment]
Hi sorry for that 
when it'll ask  you for the installation path then simply give it  /home/<your_path_here/ and it 'll work fine
If you have given a wrong path then you can edit it like this
`vim /home/hackingtoolpath.txt`
open the file and type a correct path or choose default option while installation

Thank You!

**Comment by sasddu123** [comment]
Can you give a more detailed tutorial if I put in the wrong path?
