### ISSUE TITLE
Password ?

### ISSUE THREAD

**Issue by subhradeepbhattacharta** [Z4nzu/hackingtool#151]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by D4RKH0R1Z0N** [comment]
What?

**Comment by Nerb000** [comment]
My genshin acc. was hack?? can you hack genshin impact?

**Comment by D4RKH0R1Z0N** [comment]
WHY THE HECK IS YOU COMMENT COMING WHEN I SEARCH MY NAME???

**Comment by D4RKH0R1Z0N** [comment]
Can you delete the issue?

**Comment by D4RKH0R1Z0N** [comment]
And stop the email reply that why I think its appearing?

**Comment by D4RKH0R1Z0N** [comment]
Can you please delete this issue?

**Comment by cclauss** [comment]
@Z4nzu Please close this issue.
