### ISSUE TITLE
Kbewallet ... Password 

### ISSUE THREAD

**Issue by subhradeepbhattacharta** [Z4nzu/hackingtool#152]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![IMG_20210811_104933](https://user-images.githubusercontent.com/78259659/128973657-68de72fc-80fb-4948-8a82-37f93c400b33.jpg)
![IMG_20210811_104933](https://user-images.githubusercontent.com/78259659/128973667-908942eb-4c1f-4d84-910e-2bb58b7483c8.jpg)
![IMG_20210811_104933](https://user-images.githubusercontent.com/78259659/128973691-2627b630-738c-45bb-a675-be8ef69b899e.jpg)
![Uploading IMG_20210811_104933.jpg…]()

**Comment by TTR-maniac** [comment]
You can configure the KDE wallet service in System Settings -> Account Details.
There you can enable/disable the wallet service completely or reconfigure it as necessary.

If you are interested in using the KDE Wallet service to store your login credentials for you you might create a new wallet using the New... button in the Automatic Wallet Selection section and then set that one up as the new default.
To clean up the old wallet, hit Launch Wallet Manager and then in that window select the unwanted wallet and select File -> Delete Wallet. From this window you may also change the password and review stored credentials. You can also go directly to this tool by launching the KWalletManager app.

**Comment by TTR-maniac** [comment]
**https://forum.kde.org/viewtopic.php?f=225&t=160488******
