### ISSUE TITLE
sh: 1: figlet: not found sh: 1: lolcat: not found

### ISSUE THREAD

**Issue by this-is-shashank-mishra** [Z4nzu/hackingtool#16]
**figlet** and **lolcat** need to be added in requitement.txt :
![Screenshot from 2020-07-09 09-24-16](https://user-images.githubusercontent.com/60059208/86995282-324fd700-c1c6-11ea-9480-3c2e644963ba.png)
error

**Comment by Z4nzu** [comment]
Sure sorry for that i'll add it today 😊
