### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by ammarin25455** [Z4nzu/hackingtool#166]
[sudo] password for kali: 
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>
    os.mkdir(archive)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by haydenzeller** [comment]
Did you run install.sh?

**Comment by Gabbykruiz** [comment]
No don’t know how to start it
