### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Allanjheisua** [Z4nzu/hackingtool#170]
hi

**Comment by Gabbykruiz** [comment]
I named some help right now and don't know if you're going to help me can you do me a favor?

**Comment by Allanjheisua** [comment]
what

**Comment by Gabbykruiz** [comment]
I'd like to create and post my nft and on network but I'm new to all of it and these hacking trick sound fun how can I create a token or raise ethereum for my nft

**Comment by Allanjheisua** [comment]
Sure i can help you with it Here is my whatsapp

+639668039076

**Comment by Gabbykruiz** [comment]
Ok I will text you right away

**Comment by Allanjheisua** [comment]
Awesome, thanks!

**Comment by cclauss** [comment]
Please close this non-issue.
