### ISSUE TITLE
I shit my pants

### ISSUE THREAD

**Issue by elboninjarocks** [Z4nzu/hackingtool#171]
It kinda smells

**Comment by exe9** [comment]
I had the same problem, not sure if the devs have made a fix yet

**Comment by shubham49m** [comment]
Hii bro thanks for sharing such nice tools I really like it. :D xD

**Comment by exe9** [comment]
> Hii bro thanks for sharing such nice tools I really like it. :D xD

卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐

**Comment by whoamihker** [comment]
> Hii bro thanks for sharing such nice tools I really like it. :D xD

so many tools can not use = =

**Comment by cclauss** [comment]
@Z4nzu
