### ISSUE TITLE
Tried to install it on macOS and changed the install.sh to fit macOS commands but it didn't work

### ISSUE THREAD

**Issue by IzrailAS** [Z4nzu/hackingtool#173]
**Describe the bug**
I tried to install it on macOS even though it supposed to work on Kali Linux / Parrot OS. I changed commands like "sudo apt-get install -y figlet" to "brew install figlet" or "sudo apt-get install boxes" to "brew install boxes", but the installation fails.

**To Reproduce**
1. I cloned the repo
2. used ”chmod -R 755 hackintool"
3. changed to the directory hackingtool with "cd hackingtool"
4. installed the requirements with "sudo pip3 install -r requirements.txt"
5. changed the install.sh to fit macOS command, due to not existing apt-get command on macOS. I changed them to "brew install ...." and commented them out
6. it can't create the hackingtool directory in "/usr/share/doc/" => operation not permitted
7. it can't copy to the hackingtool directory =>  => operation not permitted
8. the installation of the requirements works fine, even though I get warnings, that running pip as root is not recommended 
9. it tries to install some requirements and sees that the requirement is already satisfied and then I get the "installation failed"  message and it stops the process

**Expected behavior**
I hoped that if I change the commands in the "install.sh" to commands that work in bash/zsh on macOS like brew, that it should work, but it didn't.

**Screenshots**
look at attached screenshot

**Desktop (please complete the following information):**
 - Device: [MacBook Pro 13" 2020]
 - OS: [macOS 12.1]

<img width="1424" alt="hackingtool install error" src="https://user-images.githubusercontent.com/97174663/148240189-e31a2984-d862-4b8f-acf2-c3d32ac34eec.png">

**Comment by Akshay-Arjun** [comment]
Use chmod 777. Or give all permissions . According to 6,7 errors you haven't given enough permissions for it to create directory and the code checks for the directory to confirm installation.

**Comment by Drjacky** [comment]
- Replaced `apt-get` with `sudo`:
```
            sudo apt-get update -y && apt-get upgrade -y
            sudo apt-get install python3-pip -y
```
to 
```
            yes | brew update && yes | brew upgrade
            yes | brew install python3-pip
```
&
```
            sudo apt-get install -y figlet
```
to
```
            yes | brew install figlet
```

- And for the brew permission error: `sudo chown -R $(whoami) $(brew --prefix)/*`.

And stuck on this step:
```bash
[✔] Installing ...\n
fatal: could not create work tree dir '/usr/share/doc/hackingtool': Operation not permitted
```
