### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by awnyel** [Z4nzu/hackingtool#174]
Traceback (most recent call last):
  File "/home/kali/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/home/kali/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])

I'm getting this error someone can help? also in sudo in python3

**Comment by yousskh** [comment]
Also getting this error since yesterday, have been looking for a solution for 5 hours but nothing to do

pls tell me if you find how to solve it

**Comment by awnyel** [comment]
> Also getting this error since yesterday, have been looking for a solution for 5 hours but nothing to do
> 
> pls tell me if you find how to solve it

nothing i was on this trouble the whole night. i don't know enough about python coding and the problem is there

**Comment by Fleekshot** [comment]
Just had this same issue, tried doing the update.sh thing, deleting the folder and recloning, didn't fix.

Let me know if you find a fix

**Comment by RiskVirusPro** [comment]
@Fleekshot @yousskh  in tools/ddos.py line29 subprocess.run function the socks_type5.4.1 must be a string.
replace as "socks_type5.4.1" may solve the issue

**Comment by yousskh** [comment]
i edited the file with "sudo nano" (maybe it is not the right way), the file seems to have changed but when I execute hackingtool it gives me the error as if it had not updated it

**Comment by Fleekshot** [comment]
> @Fleekshot @yousskh in tools/ddos.py line29 subprocess.run function the socks_type5.4.1 must be a string. replace as "socks_type5.4.1" may solve the issue

I just tried that for ddos.py in both the \\wsl$\ and C:// drive directories, nothin worked.

**Comment by Fleekshot** [comment]
> @Fleekshot @yousskh in tools/ddos.py line29 subprocess.run function the socks_type5.4.1 must be a string. replace as "socks_type5.4.1" may solve the issue

Sorry about that nevermind, so basically I'm trying to edit the file but I can't through \\wsl$\ folder. I'm not exactly sure how to on the terminal. Apologies for being stupid just a little new.

**Comment by yousskh** [comment]
@Fleekshot 
you can try this
> sudo -i
> cd ..

then 2 options : 
-  > cd usr/share/doc/hackingtool/tools/
   > sudo nano ddos.py
   Edit line 29, add quotes
   
or :
-  > cd home/kali/hackingtool/tools/
   > sudo nano ddos.py
   Edit line 29, add quotes
   
_or if it doesn't work and you understood the procedure, replace after cd with the directory indicated in your error message_
   
else I don't know how I can help you, I'm not really a pro sorry

**Comment by ZoZomk6** [comment]
so has anyone found a rezolvation?

**Comment by RiskVirusPro** [comment]
> so has anyone found a rezolvation?

**Comment by RiskVirusPro** [comment]
> so has anyone found a rezolvation?
hi,have you edited the tools/ddo.py yet?

**Comment by ZoZomk6** [comment]
> > so has anyone found a rezolvation?
> > hi,have you edited the tools/ddo.py yet?

no, how can I do that?

**Comment by RiskVirusPro** [comment]
Which OS are you using?

**Comment by ZoZomk6** [comment]
> tools/ddo.py

could you help me on discord it would be easier ZoZo#7514

> Which OS are you using?

kali linux

**Comment by RiskVirusPro** [comment]
cd usr/share/doc/hackingtool/tools/
sudo vim ddos.py
Edit line 29, add quotes to socks_type5.4.1

**Comment by ZoZomk6** [comment]
> cd usr/share/doc/hackingtool/tools/

(root💀kali)-[/home/kali]
└─# cd usr/share/doc/hackingtool/tools/
cd: no such file or directory: usr/share/doc/hackingtool/tools/

**Comment by ZoZomk6** [comment]
> cd /usr/share/doc/hackingtool/tools/ ,miss a '/' at the begining

ok I am trying it

**Comment by ZoZomk6** [comment]
> sudo vim ddos.py

after I put quotes How do I save?

**Comment by ZoZomk6** [comment]
> sudo vim ddos.py

how do I save?
![image_2022-01-13_031447](https://user-images.githubusercontent.com/97643576/149248283-7f6b611f-89f4-4c93-8438-a789718d8676.png)

**Comment by ZoZomk6** [comment]
I did it but I wrote hackingtool and pressed on default and this showed up
![image_2022-01-13_033740](https://user-images.githubusercontent.com/97643576/149250233-592de41d-bdf9-4565-ad68-9bd4ddf19eec.png)

**Comment by yousskh** [comment]
@omarlang 

![Capture d’écran 2022-01-13 114055](https://user-images.githubusercontent.com/97390823/149315120-72d494cf-bc8d-47f0-86aa-8859a9f2d945.jpg)

**Comment by omarlang** [comment]
thx so much it worked

**Comment by KernelxD** [comment]
Hey @yousskh I tried to add the quotes to socks_type5.4.1 but it didn't work, what do I do?

**Comment by kali100x** [comment]
![image](https://user-images.githubusercontent.com/97807071/149666383-d800648f-cb35-4178-b522-0d2376fd6c23.jpeg)![image](https://user-images.githubusercontent.com/97807071/149666389-0c52cc27-31e5-414f-812e-0b77fdd4a5cb.jpeg)

**Comment by kali100x** [comment]
Can someone tell me what I did wrong ?? I am new in this things.
Thanks

**Comment by kali100x** [comment]
I add the quotes but still telling me syntax error

**Comment by yousskh** [comment]
> Can someone tell me what I did wrong ?? I am new in this things.
> Thanks

Its seems like you edited a wrong ddos.py file or you didn't save changes before closing the file

Also make sure to use `sudo sano` to avoid any  problem in relation with admin privileges

Ctrl + O to save, press enter to keep the same file name
Then Ctrl + X to leave

**Comment by awnyel** [comment]
thank u i edited the code and the syntax is working!

**Comment by kali100x** [comment]
There is another syntax error line 11 ‘/‘ 


Enviado desde mi iPhone

**Comment by yousskh** [comment]
> There is another syntax error line 11 ‘/‘

No, this error is not a syntax error : it occurs when you try to import the DDOSTools module, which contains the syntax error.

So if you fix the error in ddos.py, the first error will disappear

**Comment by kali100x** [comment]
Sorry for ask again but I still with the problem when I change the file and I save it with nano what I have to do write again hackingtool or reinstall the new file.
[image](https://user-images.githubusercontent.com/97807071/149679164-c18803da-b1ce-4ec6-8e08-95f3f3b7d031.jpeg)

**Comment by yousskh** [comment]
It's because you didn't edit the right ddos.py file. (idk why we get many ddos files)

Follow exactly these instructions to edit the right file :

>cd
>cd ..    _(with the two dots or it will not work)_
>cd usr/share/doc/hackingtool/tools/
>sudo nano ddos.py
> Edit line 29, add quotes

**Comment by kali100x** [comment]
Yes it's working finally !!!
