### ISSUE TITLE
SyntaxError, Traceback?

### ISSUE THREAD

**Issue by Fleekshot** [Z4nzu/hackingtool#175]
When I execute this pops up:

Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

Not sure what went wrong, I did the update.sh then after that everything stopped working. I tried deleting the folder and recloning, but that didn't work. Let me know if someone finds a fix.

Thanks

**Comment by RiskVirusPro** [comment]
same issue

**Comment by RiskVirusPro** [comment]
please see 174

**Comment by aavp13** [comment]
> please see 174

hello team, im so newbie, how i could use this packets to solve it, installing with pip3???

**Comment by Minalesa** [comment]
me pasa lo mismo ayuda

**Comment by aramsoft89** [comment]
pless help


sudo hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                     ^
SyntaxError: invalid syntax

**Comment by Kali-100** [comment]
> please see 174

how?

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
Fixed in #176
Please close this issue.
