### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by ZoZomk6** [Z4nzu/hackingtool#177]
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

**Comment by RiskVirusPro** [comment]
see #174, socks_type5.4.1 must be a string

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
Fixed in #176
Please close this issue.
