### ISSUE TITLE
After install in ubuntu 20.04

### ISSUE THREAD

**Issue by pro11neverdies** [Z4nzu/hackingtool#180]
After installation from root in ubuntu 20.04 LTS
run hackingtool from /root (with user root) :

  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])

**Comment by Ilovetechnologyman** [comment]
same :/

**Comment by king1TED** [comment]
some :|

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
Fixed in #176
Please close this issue.
