### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by feufr** [Z4nzu/hackingtool#181]
when i run the install.sh it gives me this error [✘] Installation Failed !!! [✘]
[✔] Loading ...
Hit:1 http://kali.download/kali kali-rolling InRelease
Reading package lists... Done
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate
[✔] Checking directories...
[✔] Installing ...

fatal: could not create work tree dir '/usr/share/doc/hackingtool': Permission denied

[✔] Trying to installing Requirements ...
Requirement already satisfied: lolcat in /usr/local/lib/python3.9/dist-packages (1.4)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
figlet is already the newest version (2.2.5-3+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: boxes in /usr/local/lib/python3.9/dist-packages (0.0.0)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
boxes is already the newest version (2.1.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: flask in /usr/local/lib/python3.9/dist-packages (2.0.2)
Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.9/dist-packages (from flask) (8.0.3)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.9/dist-packages (from flask) (3.0.3)
Requirement already satisfied: Werkzeug>=2.0 in /usr/local/lib/python3.9/dist-packages (from flask) (2.0.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.9/dist-packages (from flask) (2.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from Jinja2>=3.0->flask) (2.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests) (2.0.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests) (2021.10.8)
[✘] Installation Failed !!! [✘]

**Comment by Sawnoff1** [comment]
try "sudo bash install.sh" 

should work

**Comment by Z4nzu** [comment]
Fixed #348
