### ISSUE TITLE
Error. Not able to run the application

### ISSUE THREAD

**Issue by GirishKumarSharma** [Z4nzu/hackingtool#182]
┌──(root💀kali)-[/home/girish/hackingtool]
└─# hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax
                                                                                                                                                                       
┌──(root💀kali)-[/home/girish/hackingtool]
└─# lsb_release -a                                                                                                                                                 1 ⨯
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.4
Codename:       kali-rolling
                                                                                                                                                                       
┌──(root💀kali)-[/home/girish/hackingtool]
└─#

**Comment by snixd** [comment]
yes i am having the same issue. Please if anyone can help with the issue ???

**Comment by HACKER-FORUM** [comment]
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax



same issue

**Comment by Minalesa** [comment]
Mismo problema :( ayuda

**Comment by intrawvert** [comment]
same problem ;(

**Comment by stefancandrea** [comment]
Open File as root

/usr/share/doc/hackingtool/tools/ddos.py

Go to line number 29

And just Replace
socks_types5.4.1 > "socks_types5.4.1"

In other words... make that a string!

And save the file. And now go to terminal and type
sudo hackingtool
