### ISSUE TITLE
typing in hackingtool gives the following errors

### ISSUE THREAD

**Issue by ianharekr** [Z4nzu/hackingtool#183]
hackingtool          
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

any ideas
followed the instal instructions, but maybe im missing something

**Comment by fahadfarj** [comment]
same problem

**Comment by fahadfarj** [comment]
File "/home/kali/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/home/kali/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
Can you please tell me how to fix this issue

**Comment by BadWolf-ui** [comment]
Same issue

**Comment by nathanawmk** [comment]
Same issue - this doesnt work

**Comment by stefancandrea** [comment]
Open File as root

/usr/share/doc/hackingtool/tools/ddos.py

Go to line number 29

And just Replace
socks_types5.4.1 > "socks_types5.4.1"

In other words... make that a string!

And save the file. And now go to terminal and type
sudo hackingtool

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
Fixed in #176
Please close this issue.
