### ISSUE TITLE
SyntaxError: invalid syntax traceback most recent call last

### ISSUE THREAD

**Issue by usque-ad-mortem** [Z4nzu/hackingtool#185]
┌──(root💀localhost)-[~]
└─# hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

this happens when i type in "hackingtool" in terminal. any fixes?

**Comment by Killfish123** [comment]
for me too pls

**Comment by imashiqe** [comment]
Reinstall xamp

**Comment by usque-ad-mortem** [comment]
> Reinstall xamp

i did, didnt solve it

**Comment by macios123** [comment]
Just go to /usr/share/doc/hackingtool/tools/ddos.py file and change socks_type5.4.1 to "socks_type5.4.1" therefore the DDOS script is unlikely to work, but the rest should.

**Comment by lucybell89** [comment]
Hi, i can't speak english, so i try to explain of the best form who i can. To solve yout problem you need to go to the next route: "/usr/share/doc/hackingtool/", and touch the element: "hackingtool.py", with the command: "nano hackingtool.py", in that place, you need delete the whole line number 11 and 56; close and save with "ctrl+x".  

Step 2: go to this route: "/usr/share/doc/hackingtool/tools/", and touch the element: "ddos.py", in that place, just delete the whole line number 29, close and save with "crtl+x".

Go to the directory where did you install "hackingtool", and try to run the script again. Good Luck.

**Comment by LoggerBehind** [comment]
> Hi, i can't speak english, so i try to explain of the best form who i can. To solve yout problem you need to go to the next route: "/usr/share/doc/hackingtool/", and touch the element: "hackingtool.py", with the command: "nano hackingtool.py", in that place, you need delete the whole line number 11 and 56; close and save with "ctrl+x".
> 
> Step 2: go to this route: "/usr/share/doc/hackingtool/tools/", and touch the element: "ddos.py", in that place, just delete the whole line number 29, close and save with "crtl+x".
> 
> Go to the directory where did you install "hackingtool", and try to run the script again. Good Luck.

THNXS ALOT

**Comment by cacademono08** [comment]
> 


you speak Spanish I speak Spanish and if you have a discord you could help me if you want because I did not understand well my discord nickname is cacademono # 5167

**Comment by stefancandrea** [comment]
Open File as root

/usr/share/doc/hackingtool/tools/ddos.py

Go to line number 29

And just Replace
socks_types5.4.1 > "socks_types5.4.1"

In other words... make that a string!

And save the file. And now go to terminal and type
sudo hackingtool

**Comment by GSA001** [comment]
I change and save the file but it still give the same error

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
@Z4nzu

**Comment by cclauss** [comment]
Fixed in #176
Please close this issue.
