### ISSUE TITLE
from tools.ddos import DDOSTools

### ISSUE THREAD

**Issue by LoggerBehind** [Z4nzu/hackingtool#187]
# sudo hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

**Comment by ftplogan** [comment]
same please help

**Comment by stefancandrea** [comment]
Replace with "socks_type5.4.1" ---> In other words... make that a string!

**Comment by cclauss** [comment]
Fixed in #176
Please close this issue.

**Comment by MohamedHassan135** [comment]
What I do not understand anything What do you want
