### ISSUE TITLE
can not run hackingtool !!!!! SyntaxError: invalid syntax ???

### ISSUE THREAD

**Issue by samsunggalaxys22u** [Z4nzu/hackingtool#188]
# python3 ./hackingtool.py

Traceback (most recent call last):
  File "/root/hackingtool/./hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/root/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

__________________________________________________________________________________

**Comment by whoamihker** [comment]
┌──(root💀kali)-[~]
└─# hackingtool        
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

**Comment by cacademono08** [comment]
I have the same problem, is there a solution?

**Comment by Toolie7** [comment]
I followed your steps but Im stuck on permission denied . I tried chmod, Im a noob haha.

**Comment by philmacrack** [comment]
@Toolie7 "sudo" my guy,
also i had to chmod +x install.sh then sudo ./install.sh for it to install properly then alter the line to a string described above
//wl

**Comment by cclauss** [comment]
Fixed in #176
