### ISSUE TITLE
look

### ISSUE THREAD

**Issue by PhucLee8777** [Z4nzu/hackingtool#189]
![image](https://user-images.githubusercontent.com/93758292/155468650-b9d57e21-6c82-4005-a3ee-1783699e7f11.png)

**Comment by stefancandrea** [comment]
Replace with "socks_type5.4.1" ---> In other words... make that a string!

**Comment by johnson86kali** [comment]
Open File as root

/usr/share/doc/hackingtool/tools/ddos.py

Go to line number 29

And just Replace 
socks_types5.4.1     >        "socks_types5.4.1" 

In other words... make that a string!

And save the file. And now go to terminal and type
sudo hackingtool

It's worked.

**Comment by stefancandrea** [comment]
Ah... I opened the file with vsCode which is "permanetly as root" and I forgot about the root part :P

**Comment by PhucLee8777** [comment]
> Ah... I opened the file with vsCode which is "permanetly as root" (for me) and I forgot about the root part :P

how to do that

**Comment by jind75** [comment]
cant change ddos.py bcoz file is read only.

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
Fixed in #176
Please close this issue.
