### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by Flybychi** [Z4nzu/hackingtool#195]
preface: I'm not very knowledgeable about the coding aspect

Hello, I've been trying to get this program to work in the Kali Linux VM for a bit now but I'm stopped by the sock_type invalid syntax error. Ive tried putting quotation marks around it as people suggested in the root files but it still shows the syntax error.
The problem is probably just staring me in the face but I'm too much of a beginner to figure out what that issue is. any help would be appreciated.

**Comment by Flybychi** [comment]
> same

ayo found the solution from someone else 

type this into the root terminal sudo nano /usr/share/doc/hackingtool/tools/ddos.py

the ddos file should pop up in the terminal, after putting in the quote marks save it then it should work

**Comment by Khanggggggggggg** [comment]
Where do I put it the quotemarks?

**Comment by cclauss** [comment]
Fixed in #176
