### ISSUE TITLE
from tools.ddos import DDOSTools

### ISSUE THREAD

**Issue by cesarmon99** [Z4nzu/hackingtool#196]
Problem running hackingtool on linux terminal:
sudo hackingtool    
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

please help

**Comment by AmRobertJohn** [comment]
type 
sudo nano /usr/share/doc/hackingtool/tools/ddos.py
then change socks_type5.4.1 in line 29 into a string by adding quotes "socks_type5.4.1"

**Comment by Mrscherry** [comment]
SUN DEFI
 Today's top financial traders
 100% foreign capital is a reputable, reliable, high-security place for investors.
 Annual profit up to 1440%
 Profits will be transferred directly to investors' wallets every day.
 Zalo: 0584391289 meet Lily for guidance.
 Click the link for more details:
 https://www.funawealth.com?share_address=0x1813752628964484E01744527388ed5429024926

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
Fixed in #176 (merged)
Please close this issue.
