### ISSUE TITLE
cant use some tools

### ISSUE THREAD

**Issue by fakehitman** [Z4nzu/hackingtool#2]
Android hack SocialMedia Attacker etc are not working when you try to install any tool it requires username and password and after you enter them it just go back and nothing happens

**Comment by Z4nzu** [comment]
Please share me full details with screen shot  and u also send it in mail

**Comment by fakehitman** [comment]
Thank u for helping

**Comment by Z4nzu** [comment]
I have checked that issue coming because owner of the repositories@thelinuxchoice archives all that tools whenever they available publicly it automatic works ....Thank you

**Comment by fakehitman** [comment]
There are other tools too
So just install them hy myself?

**Comment by Z4nzu** [comment]
Please give me name of the other tools because I have added android tools is only one owner and that user is now blocked i'll try to add more tools for you ..😊

**Comment by fakehitman** [comment]
SocialMedia Attack
Android Hack
These 2 categories
Others seem to work
Thank u for ur help
