### ISSUE TITLE
Kali Linux not running the program

### ISSUE THREAD

**Issue by coolrex330** [Z4nzu/hackingtool#200]
I am having issues when using Kali Linux. I have installed everything correctly but get this error when I try to run it. Could you help me? I was in the folder and wrote `sudo hackingtool`
![error](https://user-images.githubusercontent.com/68957280/160708568-87851db8-0f80-4a56-8af7-85e2a5c77bd5.PNG)

**Comment by Khanggggggggggg** [comment]
I have this issues too

**Comment by bzayyat** [comment]
Go to /usr/share/doc/hackingtool/ and edit line 29 of hackingtool.py changing socks_type5.4.1 to a string "socks_type5.4.1"

**Comment by ReptilianusBileciktus** [comment]
ı don't find socks_type5.4.1

**Comment by Swetsen** [comment]
he meant /usr/share/doc/hackingtool/tools/ddos.py cause thats were the error is

**Comment by Swetsen** [comment]
just follow the exact instructions except open the ddos.py thing

**Comment by Khanggggggggggg** [comment]
> ı don't find socks_type5.4.1

Go to line 29

**Comment by botRobot8159** [comment]
Okay

**Comment by botRobot8159** [comment]
Yea
