### ISSUE TITLE
Program emits Errors. 

### ISSUE THREAD

**Issue by littlewow** [Z4nzu/hackingtool#202]
**Describe the bug**
In Kali OS, 
1. After installing using "install.sh", 
2. When type "hackingtools" 
=> Program emits **2 Errors. (1. DDOSTools, 2. AnonSurf)**

Among 2 Errors, I found a Solution related to the DDOSTools => you can refer to the solution described in here(https://github.com/Z4nzu/hackingtool/issues/196)

However, I still don't know solution for "AnonSurf"
---------------------------------------------------------------------
### Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 10, in <module>
    from tools.anonsurf import AnonSurfTools
ModuleNotFoundError: No module named 'tools.anonsurf'

Please help........

**And Above All, Thank you for your great Work ! and inspiring the best!**

**Comment by danielgauquelin** [comment]
kjh r rdfki r

**Comment by Z4nzu** [comment]
Fixed #348
