### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirement.txt' when im installing it this happens in the end

### ISSUE THREAD

**Issue by Nokuta** [Z4nzu/hackingtool#203]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by botRobot8159** [comment]
I am on a iPhone XR

**Comment by cclauss** [comment]
The file is at https://github.com/Z4nzu/hackingtool/blob/master/requirement.txt
