### ISSUE TITLE
Complete Uninstall

### ISSUE THREAD

**Issue by dkay-zaxxx** [Z4nzu/hackingtool#205]
Hi,

Great tool, however I would like to completely remove it from my system as well as all the dependencies. Is there a script for this?

Thanks,

**Comment by Swetsen** [comment]
[this](https://github.com/Swetsen/Hackingtool/blob/patch-1/uninstall.sh) script should in theory uninstall the whole program. Didn't test it yet though. Just add an executable flag and run the script as root.

**Comment by dkay-zaxxx** [comment]
Thank you, it works.

You can amend your script to the following :

**sudo rm -rf /usr/share/doc/hackingtool
sudo rm -rd /usr/bin/hackingtool
sudo pip3 uninstall lolcat
sudo apt-get remove -y figlet
sudo pip3 uninstall boxes
sudo apt-get remove -y boxes
sudo pip3 uninstall flask
sudo pip3 uninstall requests**

Thanks,
