### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by chewbyte** [Z4nzu/hackingtool#209]
**Describe the bug**

I have installed this tool successfully though when i go to run it with <sudo hackingtool> or <hackingtool> it comes up with the error I have attached as a screenshot. Why would this be happening?

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13176339/161368818-26bf3219-9ba7-4bab-a451-65d379c6d405.jpeg)

**Desktop (please complete the following information):**
 - OS: Kali

**Smartphone (please complete the following information):**
 - Device: rpi4

**Additional context**

**Comment by mak2033** [comment]
same here

**Comment by chewbyte** [comment]
Might try and rm then reinstall

**Comment by Swetsen** [comment]
edit /usr/share/doc/hackingtool/tools/ddos.py on line 29 and add quotation marks around sockstype5.4.1

**Comment by Swetsen** [comment]
Duplicate of #194 and essentially every single other issue

**Comment by chewbyte** [comment]
Got it to work after a few removes and some missed "Sudo" commands here and there

**Comment by cclauss** [comment]
Fixed in #176

**Comment by cclauss** [comment]
Fixed in #176 (merged)
Please close this issue.
