### ISSUE TITLE
Pip3 command not found

### ISSUE THREAD

**Issue by TwistedVision518** [Z4nzu/hackingtool#213]
Noticed that when trying to run the "bash install.sh" command it removes python3 and installs python2.7 which does not support pip3 i dont think its supposed to remove that package

**Comment by cclauss** [comment]
Python 2 died 824 days ago on 1/1/2020 so it is often no longer available in modern operating systems.

**Comment by cclauss** [comment]
Please close this issue as it is a duplicate of #212

**Comment by goddardYYZ** [comment]
This does not fix the issue but okay... With python3-pip the issue still persists.
