### ISSUE TITLE
can NOT run hackingtool...

### ISSUE THREAD

**Issue by G8m25** [Z4nzu/hackingtool#217]
I cannot run hackingtool 
after successfully installing hackingtool and running it for the first time i closed it by exiting and when i tried to open it again using :
cd hackingtool
hackingtool ((which should open hackingtool))
I get this message : 
python3: can't open file '/usr/share/doc/hackingtool/hackingtool.py' : [Errno 2] No such file or directory  
 I even tried sudo which didnt work
 OS: Oracle VM virtualbox kali linux 
Screen shot:
![Desktop Screenshot 2022 04 04 - 00 13 50 24](https://user-images.githubusercontent.com/80896365/161451038-f8293ecf-7229-451b-9fb5-92b40752e495.png)
**Additional context**
I updated my kali Linux system from the hackingtool (when you go to update but choose sys update) and i had some issues with the overall installtion of hackingtool which i fixed following some of the issues in this repo . pls help

**Comment by G8m25** [comment]
and my terminal window names and date and time got kinda weird as u can see in the screenshot(top right and top left) 
while trying to install the requirements or bash install.sh I gave it sudo access but i don't remember the details

**Comment by Nabil-Syahnaufal** [comment]
what is you directory use for save hackingtool?

**Comment by Nabil-Syahnaufal** [comment]
try this : 

cd hackingtool
python hackingtool.py

don't forget .py

**Comment by G8m25** [comment]
@Nabil-Syahnaufal  i used the default directory

**Comment by cclauss** [comment]
Fixed in #176 (merged)
Please close this issue.
