### ISSUE TITLE
Close 20+ open issues with one change: Add quotes around `socks_type5.4.1` in `ddos.py`

### ISSUE THREAD

**Issue by cclauss** [Z4nzu/hackingtool#218]
**Describe the bug**

___All of the following open issues can be closed___ by changing `socks_type5.4.1` --> `"socks_type5.4.1"` at
"/usr/share/doc/hackingtool/tools/ddos.py", line 29

Merge pull request #176 to fix #174, #175, #177, #178, #179, #180, #183, #185, #187, #188, #189, #193, #194, #195, #196, #200, #204, #206, #209, #215, #217

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cclauss** [comment]
Fixed in #176 (merged)
Closing this issue.

**Comment by cclauss** [comment]
I believe that the green items in the list above can all be closed.

**Comment by Z4nzu** [comment]
I'll do
