### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by kamranrafiq** [Z4nzu/hackingtool#224]
After installing the tool, I try to run it using "hackingtool" command but it's throwing the below error. Can someone help here?

┌──(root㉿kali)-[~/hackingtool]
└─# hackingtool 
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

**Comment by kamranrafiq** [comment]
IT worked. Looks like the quote is missing.

 subprocess.run([
            "sudo", "python3 ddos", "method, url, socks_type5.4.1, threads, proxylist, multiple, timer"])

**Comment by fukudaijinsama** [comment]
Hai bro how you fix the error??
