### ISSUE TITLE
cant open

### ISSUE THREAD

**Issue by kali-11ay** [Z4nzu/hackingtool#225]
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

**Comment by pnagasaikiran** [comment]
Open the file in vim or nano
sudo vim /usr/share/doc/hackingtool/tools/ddos.py 
modify the line 29
subprocess.run([
            "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])       old code
            "sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])    new code 

It will work

**Comment by Dreadox** [comment]
How do i enter in that file ? sudo vim doesnt exist

**Comment by pnagasaikiran** [comment]
> sudo vim doesnt exist

try nano instead of vim
