### ISSUE TITLE
Gathering informations

### ISSUE THREAD

**Issue by Dreadox** [Z4nzu/hackingtool#227]
I have a website with admin panel for testing, and the question is, after i used breach, and gathering informations about it, where can i find the logs, accounts, passwords, etc ? Cause im trying to find them, and i didnt find nothing

**Comment by botRobot8159** [comment]
Send me a ps4 Fortnite account

**Comment by Dreadox** [comment]
> Send me a ps4 Fortnite account

Ifi find where are all the informations, i promise that i will give you 🗡️

**Comment by botRobot8159** [comment]
Okay
