### ISSUE TITLE
Traceback (most recent call last): error after installing

### ISSUE THREAD

**Issue by highrider0602** [Z4nzu/hackingtool#228]
I started by folllowiung the installation instructions so, 

first i cloned the repo into /opt folder

next i chmod -R 755 hackingtool before i cd'd into the directory and 

proceeded to bash install.sh, followed the promts, and after it said it completed successfully 

i used sudo hacking tool and the following is what i got for outrput

Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax

------------------------------------------------------------------------------

Not sure what to do for a fix so any advice would be appreicated

**Comment by botRobot8159** [comment]
I need a Fortnite account for a ps4

**Comment by botRobot8159** [comment]
Can you send me a ps4 Fortnite account

**Comment by botRobot8159** [comment]
Because I don't have no Fortnite account

**Comment by loloboin** [comment]
Add " " to socks_type 

For example it should look like this 

sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

**Comment by chandra-bachtiar** [comment]
same problem

**Comment by Aikanaro1973** [comment]
In /root/hackingtool/tools/ddos.py

in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
"sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

In /usr/share/doc/hackingtool/tools/ddos.py

in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
"sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

Fix all two files ddos.py at the same line to fix the problem.

Solved

**Comment by highrider0602** [comment]
> 

this solved it for me, thank you
