### ISSUE TITLE
Arch Linux Support 

### ISSUE THREAD

**Issue by yasindce1998** [Z4nzu/hackingtool#231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudokit** [comment]
What makes you think it isn't supported?

**Comment by Clemorange22** [comment]
It needs apt-get command for install

**Comment by yasindce1998** [comment]
Arch Linux is a different distribution. So when I encountered with
installation screen. It only shows like 2 distributions.
1. Kali
2. Debian
There is no other distributions are showing.
