### ISSUE TITLE
SpyCam link leads to unknown page

### ISSUE THREAD

**Issue by yoavami** [Z4nzu/hackingtool#235]
**Describe the bug**
When clicking on the link the SpyCam GitHub page. You are lead to a 404 page not found error. The Link should be removed. 

**To Reproduce**
1. Go to 'README.md'
2. Click on 'SpyCam'

**Expected behavior**
Expected to get to a repo

**Desktop (please complete the following information):**
 - OS: [MacOS Monetary]
 - Browser [safari]

**Comment by Drjacky** [comment]
@yoavami How did you install/use it on macOS?

**Comment by yoavami** [comment]
@Drjacky I didn't, I just attempted to open the link through GitHub.
