### ISSUE TITLE
Error in kali linux

### ISSUE THREAD

**Issue by hantraxer0craft** [Z4nzu/hackingtool#240]
Hi
When I type hackingtool I have this error: 

`Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                         ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?`
 Ps: I installed it on nethunter

**Comment by hantraxer0craft** [comment]
![Screenshot_20220506-083037_Termux](https://user-images.githubusercontent.com/90773297/167078971-77ce3708-b564-4a0a-bb17-725f1cc10f30.jpg)

**Comment by Aikanaro1973** [comment]
In /root/hackingtool/tools/ddos.py

in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
"sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

In /usr/share/doc/hackingtool/tools/ddos.py

in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
"sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

Fix all two files ddos.py at the same line to fix the problem.

Solved

**Comment by reich96** [comment]
> In /root/hackingtool/tools/ddos.py
> 
> in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
> "sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])
> 
> In /usr/share/doc/hackingtool/tools/ddos.py
> 
> in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
> "sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])
> 
> Fix all two files ddos.py at the same line to fix the problem.
> 
> Solved


thanks this work for me

**Comment by owaisahmed3535** [comment]
Bero, I am having some problems.

**Comment by Aikanaro1973** [comment]
> 

Che tipo di problema hai
