### ISSUE TITLE
Fix bug DDos.py at line 29

### ISSUE THREAD

**Issue by Aikanaro1973** [Z4nzu/hackingtool#241]
In /root/hackingtool/tools/ddos.py

in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
               "sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

In /usr/share/doc/hackingtool/tools/ddos.py

in line 29 "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
               "sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

Fix all two files ddos.py at the same line to fix the problem.

Solved

**Comment by cclauss** [comment]
Fixed in #176
