### ISSUE TITLE
Hacking

### ISSUE THREAD

**Issue by idriskawa** [Z4nzu/hackingtool#29]

**Comment by robertyrk** [comment]
sudo: pip3: command not found
sudo: pip3: command not found
sudo: pip3: command not found
[✘] Installation Failed !!! [✘]
i am getting this error trying to install

**Comment by awanishtiwari97** [comment]
first install pip command
google it how to intsall pip 2 and pip3

**Comment by Zana-hex** [comment]
> sudo: pip3: command not found
> sudo: pip3: command not found
> sudo: pip3: command not found
> [✘] Installation Failed !!! [✘]
> i am getting this error trying to install

Try this...   apt install python3-pip
