### ISSUE TITLE
sh: number changes for tools: boxes: not found  

### ISSUE THREAD

**Issue by ghost** [Z4nzu/hackingtool#292]
sh: 2: boxes: not found
[1] Install
[2] Run
[98] Open project page
[99] Back to Information gathering tools
Select an option : 
Whenever i start or choose any tool from the list this the error that i get.
I am unable to solve it.

**Comment by hueychen27** [comment]
Use this command: `sudo apt install boxes`
You just didn't install boxes.

**Comment by hueychen27** [comment]
You could use `pip3 install boxes` if you want to install with the Python package manager.

**Comment by ShahidAkhterSec** [comment]
I  pip3 install boxes             
Requirement already satisfied: boxes in /usr/local/lib/python3.10/dist-packages (0.0.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by ShahidAkhterSec** [comment]
boxes has already been installed, still facing this issue

**Comment by hueychen27** [comment]
The easiest way is to uninstall the pip3 version of boxes is to instead use the apt version. Use, `pip3 uninstall boxes && sudo apt install boxes`. That worked for me.

**Comment by NevenLaBaleine** [comment]
for me it does not work and puts me :
"WARNING: Skipping boxes as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behavior with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv"

**Comment by hueychen27** [comment]
That means you don't have boxes installed with pip3.
`Skipping boxes as it is not installed`
So you can use `sudo apt install boxes` instead.

**Comment by cclauss** [comment]
Is this fixed?  Can it be closed?  https://github.com/search?q=repo%3AZ4nzu%2Fhackingtool+boxes

**Comment by Z4nzu** [comment]
Yes I guess this is fixed. I am closing this issue Thanks @cclauss
