### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by RubMyTummyPC** [Z4nzu/hackingtool#296]
I follow the steps 5 times but if i want "sudo hackingtool" i got this error:

Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>
    os.mkdir(archive)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by Petochek** [comment]
Hi, same problem, found a solution?
