### ISSUE TITLE
Do not Execute

### ISSUE THREAD

**Issue by kernelshock** [Z4nzu/hackingtool#3]
Hello, after following the installation steps described in the README.md file, and running under root user, the app doesnt seems to work. 
![Captura de pantalla de 2020-07-06 14-32-39](https://user-images.githubusercontent.com/44672394/86622736-c76c8900-bf96-11ea-8de7-fd48fc6340ac.png)

**Comment by Z4nzu** [comment]
Please try to run without sudo command I'll try to fix that thank you...

**Comment by recule556688** [comment]
hello
same thing nothing happen when I type "hackingtool"

**Comment by jukathaido** [comment]
I have the same problem...

**Comment by Z4nzu** [comment]
Please Update Tool Now....
