### ISSUE TITLE
Wireless attack tool

### ISSUE THREAD

**Issue by Zana-hex** [Z4nzu/hackingtool#31]
When running a tool, it gives me this error "sh: 2: boxes: not found"

**Comment by Z4nzu** [comment]
> When running a tool, it gives me this error "sh: 2: boxes: not found"

I will fix that thanks

**Comment by Z4nzu** [comment]
> When running a tool, it gives me this error "sh: 2: boxes: not found"

Can you please reply me with particular tool you have faced issue ..??

**Comment by Zana-hex** [comment]
With all the tools it gives me that error, but I can run them, the ones I can't run, are the wireless tools, I'll see how to fix it, by the way, as a recommendation, you should look at phishig tools, the shellphish tool creates the Facebook page of a strange way, I don't know if it's an error when implementing it, or "thelinuxchoice" error, that is the creator of that tool

**Comment by hector470** [comment]
Have you tried the zphisher tool.

**Comment by dexter-cmd** [comment]
Hey can you guys help me to fix a problem with gui ?  
I have installed kali in virtual box on windows 10 
But the thing is I am not able to download gui from tty1 it is showing me error

**Comment by Z4nzu** [comment]
> Hey can you guys help me to fix a problem with gui ?  
> I have installed kali in virtual box on windows 10 
> But the thing is I am not able to download gui from tty1 it is showing me error 

Please send error message image and please check you have enabled Virtualization in BIOS

**Comment by dexter-cmd** [comment]
> > Hey can you guys help me to fix a problem with gui ?  
> > I have installed kali in virtual box on windows 10 
> > But the thing is I am not able to download gui from tty1 it is showing me error 
> 
> Please send error message image and please check you have enabled Virtualization in BIOS

It's is showing command not found from where should I enable virtualization in bios

**Comment by Z4nzu** [comment]
> Hey can you guys help me to fix a problem with gui ?  
> I have installed kali in virtual box on windows 10 
> But the thing is I am not able to download gui from tty1 it is showing me error 

Please check Description i have made video on how to install Kali Linux CLI in windows10 without virtual box
