### ISSUE TITLE
Target not found: 'yay'

### ISSUE THREAD

**Issue by FuexFollets** [Z4nzu/hackingtool#334]
**There is a small bug that I have in the installation**
I am currently on Arch Linux and after it updated all the packages, there was an installation error  that said:
```
error: target not found: yay
```

**To Reproduce**
This happened after I entered the repository directory, ran `bash install.sh`, and selected option 2. Then, it updates all the packages and instead of installing, prints an error message `error: target not found: yay` and exits.

**Desktop:**
 - OS: Arch Linux x86_64
 - Shell: fish

**Comment by furknozg** [comment]
I think the default arch repo does not contain yay, so it has to be finnessed by cloning from Arch user repo and manually installing. I have proposed a fix but am not able to test it myself, if you can do so test it and see if it works?
https://github.com/Z4nzu/hackingtool/pull/345

**Comment by Z4nzu** [comment]
I have fixed it. Please reopen if the issue is still persistence.
