### ISSUE TITLE
Hack  password 

### ISSUE THREAD

**Issue by Vajies64** [Z4nzu/hackingtool#338]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Vajies64** [comment]
I want to find my partner's WhatsApp password without her knowing

**Comment by underdog307** [comment]
> I want to find my partner's WhatsApp password without her knowing

Put a keylogger on their phone or computer idiot

**Comment by mathiasdolleris** [comment]
i want my freinds pc password without him knowing

**Comment by Allinfoplug** [comment]
i have the both software
