### ISSUE TITLE
Module not found error ..

### ISSUE THREAD

**Issue by kapilwagh77** [Z4nzu/hackingtool#34]
![IMG_20200712_104021](https://user-images.githubusercontent.com/67738041/87239397-45fc7700-c42c-11ea-8af5-42888af53ada.jpg)

**Comment by Z4nzu** [comment]
Install all module using
'''
pip3 install -r requirements.txt

'''
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by awanishtiwari97** [comment]
first u go in hackingtool by cd hackingtool then give command
(./install.sh) and hit enter then run this tool

**Comment by kapilwagh77** [comment]
![IMG_20200712_120201.jpg](https://user-images.githubusercontent.com/67738041/87240493-a80ea980-c437-11ea-801e-25dbff8309ae.jpg)
