### ISSUE TITLE
fix:Fix some country and area can't adopt "Checking Internet Connection"

### ISSUE THREAD

**Issue by jerjjj** [Z4nzu/hackingtool#341]
**Is your feature request related to a problem? Please describe.**
problem:some country and area can't adopt "Checking Internet Connection" when they install this tool

**Describe alternatives you've considered**
replace the url(www.google.com) to "www.github.com" in install.sh,because the google not support some country or area

**Comment by Z4nzu** [comment]
Fixed #348
