### ISSUE TITLE
Typos found by codespell

### ISSUE THREAD

**Issue by cclauss** [Z4nzu/hackingtool#347]
./tools/xss_attack.py:107: vulnerabilites ==> vulnerabilities
./tools/information_gathering_tools.py:87: Scaning ==> Scanning
./tools/information_gathering_tools.py:117: informations ==> information
./tools/information_gathering_tools.py:168: informations ==> information
./tools/forensic_tools.py:60: Aquire ==> Acquire
./tools/wireless_attack_tools.py:51: bluetooh ==> bluetooth
./tools/webattack.py:89: analizing ==> analyzing
./tools/phising_attack.py:40: enginee ==> engine
./tools/phising_attack.py:95: Engagment ==> Engagement
./tools/payload_creator.py:89: writen ==> written
./tools/others/socialmedia_finder.py:53: Usege ==> Usage

**Comment by Z4nzu** [comment]
Working on this Thanks

**Comment by cclauss** [comment]
$ `py -m pip install codespell`
$ `codespell -w .`

**Comment by cclauss** [comment]
Once these typos are fixed then the `|| true` can be removed from lint_python.yml#L25 to make `codespell` a mandatory test.  https://github.com/Z4nzu/hackingtool/blob/master/.github/workflows/lint_python.yml#L25
