### ISSUE TITLE
Installation Failed!

### ISSUE THREAD

**Issue by supernova20-x** [Z4nzu/hackingtool#35]
I have done all of the steps in the terminal of the installation, and when I get to the ./install.sh
 command, I press enter and press 1 (because I am on kali linux) this pops up and when finished, if I try to run sudo hackingtool it says that the command does not exist.
![Screenshot 2020-07-12 08:00:35](https://user-images.githubusercontent.com/68188014/87245860-20b13e00-c417-11ea-9594-b4934eaf9ac1.png)

Thank you for your help! <3

**Comment by devomaa** [comment]
Run `su root` (enter root password), and try again.
