### ISSUE TITLE
target not found yay and python-pip.19.1.1-1

### ISSUE THREAD

**Issue by RavenLinuxUser** [Z4nzu/hackingtool#354]
i have a problem when i try to run bash install.sh it says error target not found yay, python-pip.19.1.1-1 , i have installed the yay and i have no idea how to install python-pip so i need help.

OS: Arch linux 64x_86X
shell: bash 5.1.6
![image](https://user-images.githubusercontent.com/127435098/224668316-8f1bfd93-6f01-4264-b70d-19ebef17382f.png)

**Comment by RavenLinuxUser** [comment]
btw im a dumass i started arch few months ago...

**Comment by mit0za** [comment]
Hi, Since you're using arch and you have already installed yay you should go to 74 lines of install.sh and change it from `sudo pacman -S python-pip-19.1.1-1 yay -y` to `sudo pacman -S python-pip` then the script should work. Hope this help
