### ISSUE TITLE
Internet connection problem

### ISSUE THREAD

**Issue by UnkownPlayerX000** [Z4nzu/hackingtool#366]
**Describe the bug**
So when I launch the bash install.sh command and I am asked which os I want to install no matter what I choose its gonna give me an error saying that there is no Internet connection although I am connected to the WiFi I don't know why this is happening

**To Reproduce**
1. Download the tool
2.cd to it
3.launch the install.sh using bash

**Expected behavior**
Install any os like normal

**Screenshots**
![Screenshot_20230606-010713_Termux.jpg](https://github.com/Z4nzu/hackingtool/assets/118047020/83ff3066-434e-4469-a802-ee5b4cf09e27)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Galaxy note 10+
 - OS:Android 12
 - Browser: Brave
 - Version 1.51.121 Chromium: 113.0.5672.163 (Official Build) (64-bit) 

**Additional context**

**Comment by Joe16g** [comment]
I have the same problem can you help me?
