### ISSUE TITLE
Tools Installation error

### ISSUE THREAD

**Issue by ksr124** [Z4nzu/hackingtool#369]
Tools installation error,

Facing the following error

@] Set Path (All your tools will be installed in that directory)
                        [1] Manual 
                        [2] Default
                
Z4nzu =>> 2
Traceback (most recent call last):
  File "/usr/share/hackingtool/hackingtool.py", line 95, in <module>
    with open(fpath, "w") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/hackingtoolpath.txt'
![Screenshot 2023-06-13 183534](https://github.com/Z4nzu/hackingtool/assets/37403798/5f22e390-70cd-4730-a881-7134cb0742cb)

**Comment by arteczx** [comment]
sudo

**Comment by cclauss** [comment]
Please try `[1] Manual` and then `~/hackingtool`
