### ISSUE TITLE
Enter Path (with Directory Name) >>  getting error plase solve this problem

### ISSUE THREAD

**Issue by kingkali07** [Z4nzu/hackingtool#372]
Enter Path (with Directory Name) >> /usr/local/sbin:/usr/local/bin:/usr/sbin:
Traceback (most recent call last):
  File "/usr/share/hackingtool/hackingtool.py", line 90, in <module>
    with open(fpath, "w") as f:
         ^^^^^^^^^^^^^^^^

**Comment by cclauss** [comment]
Duplicate of #371

**Comment by cclauss** [comment]
@kingkali07 Can this issue be closed or is there a documentation todo?
