### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by 404S1lver** [Z4nzu/hackingtool#406]
When i try to install the requirements i keep getting this error thing.
![image_2023-08-20_113736959](https://github.com/Z4nzu/hackingtool/assets/142717137/c81a6773-3a9a-479d-8cc4-dc3e71816112)

**Comment by conacts** [comment]
Step : 2 Give Permission to hackingtool
```sh
chmod -R 755 hackingtool
```
Step : 3 Move to hackingtool directory
```sh
cd hackingtool
```
Step : 4 Run hackingtool
```sh
sudo bash install.sh
```
Step : 5 For installing tools in directory
```sh
sudo hackingtool
```
