### ISSUE TITLE
hack

### ISSUE THREAD

**Issue by yash9694577** [Z4nzu/hackingtool#42]

**Comment by girirajsingh319** [comment]
Bro I want to hack an insta account so can you help me for this

**Comment by nnachiketchaudhari** [comment]
Bro I will try

**Comment by nnachiketchaudhari** [comment]
But I m biggnner

**Comment by hector470** [comment]
Yeah forward me the client name.

**Comment by jerryhothack** [comment]
Can you teach how to go about it

**Comment by girirajsingh319** [comment]
Jhanvi_kanwar_7 username

It's an fake account he uploads my gf pics on this account or meri use
dhamki bhi de rha h ki tumhara account hack karwa Dunga or bhi bahut galat
kaam kar rha h is I'd se so that's why I want to hack this id

**Comment by girirajsingh319** [comment]
jhanvi_kanwar_7 it's an user name of this I'd jisko m hack karwana chatha hu

**Comment by hector470** [comment]
Are you using a smart phone or a laptop?

**Comment by jerryhothack** [comment]
A smart phone

**Comment by nnachiketchaudhari** [comment]
No

**Comment by dexter-cmd** [comment]
Hey ! is there anyone how can help me to with my gui problem of kali ?
Yesterday I installed kali but my gui downloading fail and I stuck on tty1 I am trying to download it from there I am getting still it is failings any fix 
If you wanna know code I used to download please reply

**Comment by hector470** [comment]
Are you on what's apl

**Comment by dexter-cmd** [comment]
> Are you on what's apl

Noo I am using windows and I installed it in virtual box
