### ISSUE TITLE
I have rats for you

### ISSUE THREAD

**Issue by webmaster-exit-1** [Z4nzu/hackingtool#422]
I probably have the largest collection of RATS some of which you may want to check out. 
[185 Rats](https://github.com/webmaster-exit-1/185-remote-administration-tools)

**Comment by ne0YT** [comment]
the idea of the repo is to have a slim footprint and not including everythign there is, but only the best, if possible tools which are still being developed.

**Comment by webmaster-exit-1** [comment]
I was just sharing. Maybe something in the rat repo could help. No worries man.
