### ISSUE TITLE
problem with "git clone ..." command. 

### ISSUE THREAD

**Issue by PanewPepelqnkata** [Z4nzu/hackingtool#445]
git clone https://github.com/Z4nzu/hackingtool
Cloning into 'hackingtool'...
fatal: unable to access 'https://github.com/Z4nzu/hackingtool/': Could not resolve host: github.com

Absolutely unsolvable. Running in kali linux as root, not on a VM, git clone works

**Comment by m-attz** [comment]
You must use a URL that contains a **".git"**.

git clone https://github.com/Z4nzu/hackingtool.git
