### ISSUE TITLE
Instagram password

### ISSUE THREAD

**Issue by Deepak47hk** [Z4nzu/hackingtool#460]
**Describe the bug**
A clear and concise description of what the bug is.password

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Deepak47hk** [comment]
Get Instagram password 
Usher name vamini_nareti_

**Comment by Sahitya0satya** [comment]
Can u please get the Instagram password of the acc :thv
