### ISSUE TITLE
Hack tools

### ISSUE THREAD

**Issue by hema203** [Z4nzu/hackingtool#481]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chwangmin** [comment]
![금융아이콘_SVG_카카오뱅크](https://github.com/user-attachments/assets/ab1d71e1-dee0-4e4f-b14c-c9b69ae34873)
![금융아이콘_SVG_우리](https://github.com/user-attachments/assets/67d78d0d-fa38-4c89-80ad-9a0b7f94d9c4)
![금융아이콘_SVG_신한](https://github.com/user-attachments/assets/a184dbf1-16c5-44db-9a80-61ae1be5d33e)
![금융아이콘_SVG_IBK](https://github.com/user-attachments/assets/ae673794-3189-4f49-a539-d0a10ea71b9b)
![금융아이콘_SVG_KB](https://github.com/user-attachments/assets/d38feab2-80bf-4148-b2cd-0f2c5b205520)
![금융아이콘_SVG_하나](https://github.com/user-attachments/assets/6e05566a-2cce-4bb5-b287-cd2905e1f2e3)
