### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by Bapun90** [Z4nzu/hackingtool#57]

**Comment by clark10242** [comment]
Hi im new can you are teach me how i crack password with termux please

**Comment by Z4nzu** [comment]
> Hi im new can you are teach me how i crack password with termux please
> 

Please don't open new issue for this kind of question directly message on twitter and for twitter lots of tools available on GitHub please check ...

**Comment by q97585248** [comment]
Im new too, dude
Maybe hydra?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: clark10242<mailto:notifications@github.com>
发送时间: 2020年7月15日 9:23
收件人: Z4nzu/hackingtool<mailto:hackingtool@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [Z4nzu/hackingtool] Nice (#57)


Hi im new can you are teach me how i crack password with termux please

―
