### ISSUE TITLE
*Getting permission denied

### ISSUE THREAD

**Issue by presmedia002** [Z4nzu/hackingtool#58]
*Getting permission denied

                [@] Set Path (All your tools will be install in that directory) 
                        [1]Manual 
                        [2]Default
                
Z4nzu >> 1
Enter Path(with Directory Name) >> file:///home/sandhuz/hackingtool 
Traceback (most recent call last):
  File "hackingtool.py", line 2470, in <module>
    file =open(fpath,"w")
PermissionError: [Errno 13] Permission denied: '/home/hackingtoolpath.txt'
┌─[✗]─[sandhuz@parrot]─[~/hackingtool]
└──╼ $

**Comment by Z4nzu** [comment]
Run hackingtool as a root *
