### ISSUE TITLE
Checking Internet Connection ....

### ISSUE THREAD

**Issue by Beginner-yms** [Z4nzu/hackingtool#60]
# Checking Internet Connection
 when I run the "bash install.sh" and input '1' . Just  show [*] 
Checking Internet Connection ..
Please Check Your Internet Connection ..!!
Why?I used the SSR proxy,but close show Please Check Your Internet Connection ..!! too.

**Comment by Beginner-yms** [comment]
ok。I find I can't go to Google,so..... I think you don't test  Google for test network....

**Comment by FromAlaska** [comment]
> # Checking Internet Connection
> 
> when I run the "bash install.sh" and input '1' . Just show [*]
> Checking Internet Connection ..
> Please Check Your Internet Connection ..!!
> Why?I used the SSR proxy,but close show Please Check Your Internet Connection ..!! too.

What does your terminal output look like?

**Comment by Beginner-yms** [comment]
Like this :Please Check Your Internet Connection ..!!
Just for I I can't access Google.Emmm, I am in China,so I change the   install.sh -> 43 line to    " if true; then ........"
then I made it.So I think you can change test google  to other website.

**Comment by Beginner-yms** [comment]
> > # Checking Internet Connection
> > when I run the "bash install.sh" and input '1' . Just show [*]
> > Checking Internet Connection ..
> > Please Check Your Internet Connection ..!!
> > Why?I used the SSR proxy,but close show Please Check Your Internet Connection ..!! too.
> 
> What does your terminal output look like?

look up
