### ISSUE TITLE
Getting error in windows

### ISSUE THREAD

**Issue by rishabh62** [Z4nzu/hackingtool#61]
Hi, I'm getting installation failed while running install.sh file
![image](https://user-images.githubusercontent.com/11345621/87711872-83af2600-c7c5-11ea-9926-cc364ec6f2cd.png)

**Comment by uzoma16** [comment]
Window what

**Comment by Z4nzu** [comment]
> Hi, I'm getting installation failed while running install.sh file
> ![image](https://user-images.githubusercontent.com/11345621/87711872-83af2600-c7c5-11ea-9926-cc364ec6f2cd.png)
> 

Run one more time install.sh script with sudo command because installation failed 
```
sudo bash install.sh
```
