### ISSUE TITLE
': not a valid identifierad: `choice

### ISSUE THREAD

**Issue by claudiobosetti** [Z4nzu/hackingtool#62]
After the execution of ./install.sh, the tool in Kali Linux Windows 10 Subsystem gives me this error:

```
': not a valid identifierad: `choice
./install.sh: line 73: syntax error near unexpected token `else'
'/install.sh: line 73: `        else
```

How can I solve this? I've already tried with ``` sudo ```, but nothing change. I thinks that it could be a WSL problem.

Tested on Kali Linux Subsystem (Windows 10 64bit Machine)
Using python3

**Comment by Z4nzu** [comment]
Please provide screen shot ...

**Comment by claudiobosetti** [comment]
![1](https://user-images.githubusercontent.com/57715060/87858189-65b00580-c92c-11ea-8b40-8e2c9c70487b.png)

Done.

**Comment by Z4nzu** [comment]
> ![1](https://user-images.githubusercontent.com/57715060/87858189-65b00580-c92c-11ea-8b40-8e2c9c70487b.png)
> 
> Done.

I think you are running this tool in Windows OS please change it to Kali... because this error comes in Windows and if it's not solve then run below command 
```
sudo apt-get install dos2unix
```
```
dos2unix [file]
```
If it's work or not reply of this issue 😊

**Comment by claudiobosetti** [comment]
> 
> 
> > ![1](https://user-images.githubusercontent.com/57715060/87858189-65b00580-c92c-11ea-8b40-8e2c9c70487b.png)
> > Done.
> 
> I think you are running this tool in Windows OS please change it to Kali... because this error comes in Windows and if it's not solve then run below command
> 
> ```
> sudo apt-get install dos2unix
> ```
> 
> ```
> dos2unix [file]
> ```
> 
> If it's work or not reply of this issue 😊

Ok
- I was and I am on Kali
- I tried with dos2unix but it isn't working

I tried on vm and it obviously works. So, no problem, I thinks is just a WSL problem
