### ISSUE TITLE
Is this hacking tool supported with raspberry pi OS?

### ISSUE THREAD

**Issue by hackercyclops12** [Z4nzu/hackingtool#66]
If not so can I help develop a 
"Rasberry pi version"
I'm always willing to help improve both compatibility and functionality (if you don't mind of course)

**Comment by Z4nzu** [comment]
No I think it's not compatible because every tools not provide functionality like work on every platform that's why I have mentioned only Linux in platform if you tested and work then please inform me on twitter 😊And if we have to create tool for raspberry pi we try 😉
