### ISSUE TITLE
Tools not working after installing (1) en Running (2)

### ISSUE THREAD

**Issue by rayabee** [Z4nzu/hackingtool#67]
I installed the Hackingtools and i think it's an awesome tool if it works.

After installing (and running as root) i tried several tools.
The installation works fine, don't see any errors, but when i try to exectue a tool, it just refreshes the screen (terminal in Kali) and i think that is the check if the tool is installed or not. I tried it with several tools, but for example from the main menu, option 6 Web Attack Tool, then option 1 Web2Attack and then option 1 to install and then option 2 to run. Just a quick refresh of the terminal screen and no error.

Will try later on Parrot and another version of Kali, will keep you posted.

Edit: the tools in the folder hackingtool do work when i run them directly.

**Comment by Z4nzu** [comment]
> I installed the Hackingtools and i think it's an awesome tool if it works.
> 
> After installing (and running as root) i tried several tools.
> The installation works fine, don't see any errors, but when i try to exectue a tool, it just refreshes the screen (terminal in Kali) and i think that is the check if the tool is installed or not. I tried it with several tools, but for example from the main menu, option 6 Web Attack Tool, then option 1 Web2Attack and then option 1 to install and then option 2 to run. Just a quick refresh of the terminal screen and no error.
> 
> Will try later on Parrot and another version of Kali, will keep you posted.
> 
> Edit: the tools in the folder hackingtool do work when i run them directly.  
> 
> 

Kindly provide Screenshot or video so I'll fix it because in my system it works fine 😊..
