### ISSUE TITLE
error with social media bruteforce

### ISSUE THREAD

**Issue by zizotron** [Z4nzu/hackingtool#70]
I have a problem with the Instagram hack tool,
for some reason after adding the wordlist generator, it gives me an error "Python, command not found"

im not sure if its because i cant add the correct wordlist, or if there is a bug.

**Comment by Z4nzu** [comment]
> I have a problem with the Instagram hack tool,
> for some reason after adding the wordlist generator, it gives me an error "Python, command not found"
> 
> im not sure if its because i cant add the correct wordlist, or if there is a bug.

Make sure you installed tool properly...and try to run manually if it's work then please send me error image of the terminal...
