### ISSUE TITLE
error: Not a recognized archive type

### ISSUE THREAD

**Issue by sarvottam99** [Z4nzu/hackingtool#72]
**Describe the bug**
error: Not a recognized archive type: /tmp/easy_install-ovcjcgu1/Twisted-19.7.0.tar.bz2

**To Reproduce**
after executing sudo python3 setup.py install

**Screenshots**
![ss](https://user-images.githubusercontent.com/68839186/88552853-32632a00-d042-11ea-833f-11898110ec52.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux Version 2020.2

**Comment by Z4nzu** [comment]
> **Describe the bug**
> error: Not a recognized archive type: /tmp/easy_install-ovcjcgu1/Twisted-19.7.0.tar.bz2
> 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> after executing sudo python3 setup.py install
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> ![ss](https://user-images.githubusercontent.com/68839186/88552853-32632a00-d042-11ea-833f-11898110ec52.png)
> 
> **Desktop (please complete the following information):**
>  - OS: Kali Linux Version 2020.2
> 
> 

Thank you for contacting...but I think this error occurred because of specific WiFi pumpkin tool library related you have to visit WiFi pumpkin GitHub page and open an issue for error...
Thank you... Happy Hacking ⌨️😊
