### ISSUE TITLE
nmap

### ISSUE THREAD

**Issue by infoinline** [Z4nzu/hackingtool#77]
I have installed the git as required and have tried to use the nmap feature. I select nmap the install and it installs all the requirements but then goes back to the option Install or Back.
Any help is appreciated.

Thanks

**Comment by Z4nzu** [comment]
> 
> I have installed the git as required and have tried to use the nmap feature. I select nmap the install and it installs all the requirements but then goes back to the option Install or Back.
> Any help is appreciated.
> 
> Thanks 
> 

Thank you for installing hackingtool and raise your issue. In hackingtool all tools are not automatic run some tools are directly run as the owner of the tool make it but nmap is not for that you need to run it manually by using nmap commands for that please find online commands or message me on twitter I'll give you cheat sheet of nmap commands. Now I think it's clear for you and if not DM me on twitter ...!!
