### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by snaildos** [Z4nzu/hackingtool#80]
Will windows support be added? I'm happy to contribute :D

**Comment by Z4nzu** [comment]
> Will windows support be added? I'm happy to contribute :D

Contact on Twitter... We'll discuss there..!!

**Comment by QamarShaikh21** [comment]
How to run this command in ios in ISH shell

**Comment by snaildos** [comment]
@Z4nzu Alright, I dont have twitter, I'll sign up tonight :)

**Comment by snaildos** [comment]
> > Will windows support be added? I'm happy to contribute :D
> 
> Contact on Twitter... We'll discuss there..!!

What is your Twitter Username?

**Comment by ellandor** [comment]
@snaildos https://twitter.com/_Zinzu07
