### ISSUE TITLE
iPhone issue

### ISSUE THREAD

**Issue by QamarShaikh21** [Z4nzu/hackingtool#81]
How to run this on IOS in ISH shell. I am already in your telegram group thanks

**Comment by Z4nzu** [comment]
> How to run this on IOS in ISH shell. I am already in your telegram group thanks

Sorry..!! But this tool is work on Linux system it's not made for ISO system.!! 

And one more thing I have no made any telegram group yet ..So please contact on Twitter the link of twitter is given in Readme.md file.!!

Thank You..!!
Happy Hacking ..!!

**Comment by kinqcoded** [comment]
I have received your mail massege. Thank you for sharing I will check  out
on you on Twitter.
