### ISSUE TITLE
When i add the word list it appears "can't open file"

### ISSUE THREAD

**Issue by candyschnapp** [Z4nzu/hackingtool#82]
Please help, when I try to add the word list it appears 
python: can't open file 'instabrute.py" : [Errno 2] no such file or directory

Preview:
Enter Username: test12345
Enter wordword: test1.txt
python: can't open file 'instabrute.py" : [Errno 2] no such file or directory
Please help, what command should I add or what?

**Comment by Z4nzu** [comment]
> Please help, when I try to add the word list it appears 
> python: can't open file 'instabrute.py" : [Errno 2] no such file or directory
> 
> Preview:
> Enter Username: test12345
> Enter wordword: test1.txt
> python: can't open file 'instabrute.py" : [Errno 2] no such file or directory
> Please help, what command should I add or what? 

Send details with image error tool name so i can see what's the problem ..!!
