### ISSUE TITLE
App wont open

### ISSUE THREAD

**Issue by blackpyros** [Z4nzu/hackingtool#86]
Hello,

I am trying to start up this tool but after instalation it wont open.

**Error** :

[✔] Successfuly Installed !!!                                                                           
 
 
                [+]+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[+]                     
                [+]                                                             [+]                     
                [+]     ✔✔✔ Now Just Type In Terminal (hackingtool) ✔✔✔         [+]                     
                [+]                                                             [+]                     
                [+]+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[+]                     
root@kali:~/hackingtool# hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>
    os.mkdir(archive)
FileNotFoundError: [Errno 2] No such file or directory: ''

I am running kali linux on VM.
I have also tried to bash update.sh but after it end it still wont open.

Any suggestion what to do ?

Thaaanks

**Comment by Z4nzu** [comment]
Try to install one more time it'll work or not if not than please let me know ..!!
