### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wok3n** [Z4nzu/hackingtool#89]
Getting this error - 

`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory                                                                           
Traceback (most recent call last):                                                                                                                                                            
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>                                                                                                                     
    os.mkdir(archive)                                                                                                                                                                         
FileNotFoundError: [Errno 2] No such file or directory: "xxxxxxxxxxxxxx"`                                                                                      

when I reinstall and overwrite the script. Every time I reinstall and replace, it keeps a bad destination path.
Is there any way to resolve this?

**Comment by TuncUzun** [comment]
cut and copy your main HACKINGTOOL folder(where is your hackingtools right now) to "/usr/share/doc" directory then issue resolved.

**Comment by Z4nzu** [comment]
I hope your issue had resolved..So now I'm closing this issue 👍 and if not please let me know here.
Thanks @TuncUzun for watching issues and giving reply to him 👍👋
