### ISSUE TITLE
userrecon tool not found

### ISSUE THREAD

**Issue by FromAlaska** [Z4nzu/hackingtool#9]
Userrecon is not found. Can't install userrecon.

https://github.com/thelinuxchoice/userrecon/ returns a 404 error

**Comment by Z4nzu** [comment]
Ya thank you for opening issue but when I added tools it's working fine but sometimes owner of the tool can archives that or delete tool or make it private so it'll not install I'll remove that in next update ..😊Happy Hacking..⌨️
