### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by benthemarauder** [Z4nzu/hackingtool#92]
Hi can i get a link for this like this : https://repl.it/repls/GaseousFormalAttributes
So that I can use it on google?

**Comment by benthemarauder** [comment]
@Z4nzu

**Comment by Z4nzu** [comment]
> @Z4nzu 
> 

Hey @benthemarauder  I'll try and find it out. It it's possible then it will available for you in few days.
Thank you 😊
Happy Hacking 👨‍💻

**Comment by benthemarauder** [comment]
well @Z4nzu is it availible?

**Comment by Z4nzu** [comment]
> well @Z4nzu is it availible?

It's not available now because it needs lots of changes and also need more time to develop for repl. But till then you can directly use that tools by copying link from README.md 😊

**Comment by Sinzu000** [comment]
I'd absolutely appreciate it, if you could teach me advance coding. Please!
🙏🙏🙏

**Comment by benthemarauder** [comment]
hey @Z4nzu can you lmk when its ready because most stuff doesn't work for me since I'm on mac. an repl.it works for me

**Comment by benthemarauder** [comment]
whennnnnnnnnnnnnnnn its been 14 days
