### ISSUE TITLE
Cant Open

### ISSUE THREAD

**Issue by TheGoblinSociety** [Z4nzu/hackingtool#96]
When I type "sudo hackingtool" it says: python3: can't open file '/usr/share/doc/hackingtool/hackingtool.py': [Errno 2] No such file or directory

Why does it say this?

**Comment by paopaoDND** [comment]
![Capture](https://user-images.githubusercontent.com/73062884/96366761-600cca80-117c-11eb-8ecc-2cad2f81dee9.JPG)
I have the same thing. What should I do?

**Comment by Z4nzu** [comment]
Hello !! 
Please provide whole screen snap instead of crop and try to install one more time this issue happen sometimes some issues were closed related this try to find from them !!
