### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by benthemarauder** [Z4nzu/hackingtool#98]
Could you help whit running this on repl https://repl.it/@benhangin/hackingtool#README.md

**Comment by benthemarauder** [comment]
i think i messed up somewhere

**Comment by Z4nzu** [comment]
> i think i messed up somewhere

As per your last issue I had checked it if it work for all the tools that avail in hackingtool or not but it's not !! Because it also asked for Root access and repl don't give it ! Wait for few weeks I'll develop tool that has more tools then this !! 😄🤗
