### ISSUE TITLE
How to fix this ??

### ISSUE THREAD

**Issue by TURBO-gif** [Z4nzu/hackingtool#99]
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>
    os.mkdir(archive)
![photo_2020-10-27_16-34-44](https://user-images.githubusercontent.com/66200334/97293216-5ec15900-1872-11eb-84f2-88fb6d26a5a0.jpg)

**Comment by Z4nzu** [comment]
> Traceback (most recent call last):
>   File "/usr/share/doc/hackingtool/hackingtool.py", line 106, in <module>
>     os.mkdir(archive)
> ![photo_2020-10-27_16-34-44](https://user-images.githubusercontent.com/66200334/97293216-5ec15900-1872-11eb-84f2-88fb6d26a5a0.jpg)
> 

It look like you had try to change the script and run it again. Uninstall it and try to reinstall without doing any changes ..
